spring:
  application:
    name: currency-exchange
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currency_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
scheduling:
  cron: "0 0 0/1 * * ?"

currency:
  baseUrl: "https://api.freecurrencyapi.com/v1/"
  accessKey: "fca_live_r1zNa4HgLIEX7ra7pKva01HOYCROhwCnBsCQTCtl"
springdoc:
  api-docs:
    path: "/api-docs"

